Repository boostcampwm-2024/refactor-web22-LiBoo, pull requests merged in 2025-01, with the labels that each got.

#8 suspense delay 추가 및 default 이미지 수정
  frontend/src/components/common/AsyncBoundary.tsx
  frontend/src/components/main/LiveVideoCard.tsx
Labels: bug

#12 [REFACTOR] 검색 바 추가
  frontend/src/components/common/SearchHeader.tsx
  frontend/src/components/main/index.ts
  frontend/src/hooks/useDebounce.ts
Labels: FEAT, REFACTOR, FE🎄

#13 [REFACTOR] 채팅 컴포넌트 구조 개선
  frontend/src/apis/queries/chat/useFetchChatRule.ts
  frontend/src/components/chat/ChatHeader.tsx
  frontend/src/components/chat/ChatInput.tsx
  frontend/src/components/chat/ChatItem.tsx
  frontend/src/components/chat/ChatList.tsx
  frontend/src/components/chat/ChatQuestionSection.tsx
  frontend/src/components/chat/ChatRoomContainer.tsx
  frontend/src/components/chat/ChatRoomView.tsx
  frontend/src/components/chat/ClientChatRoom.tsx
  frontend/src/components/chat/HostChatRoom.tsx
  frontend/src/components/chat/LayerPopup.tsx
  frontend/src/components/chat/NoticeCard.tsx
  frontend/src/components/chat/QuestionCard.tsx
  frontend/src/components/chat/UserInfoCard.tsx
  frontend/src/components/chat/index.ts
  frontend/src/contexts/ChatSessionContext.tsx
  frontend/src/contexts/ChatUIContext.tsx
  frontend/src/contexts/ChatWorkerContext.tsx
  frontend/src/hooks/useChatRoom.ts
  frontend/src/pages/ClientPage.tsx
  frontend/src/pages/HostPage.tsx
  frontend/src/reducers/actionCreators.ts
  frontend/src/reducers/chatUIReducer.ts
Labels: REFACTOR, FE🎄

#16 [Refactor] Lighthouse 점수 개선
  backend/mainServer/src/common/constants.ts
  backend/mainServer/src/dto/liveCurationDto.ts
  backend/mainServer/src/dto/replayVideoDto.ts
  backend/mainServer/src/mock-data/mock-data.service.ts
  frontend/package.json
  frontend/public/robots.txt
  frontend/src/components/client/PlayerInfo.tsx
  frontend/src/components/common/BoostBanner.tsx
  frontend/src/components/main/LiveVideoCard.tsx
  frontend/src/components/main/RecommendLive.tsx
  frontend/src/components/main/ReplayVideoCard.tsx
  frontend/src/components/replay/PlayerInfo.tsx
  frontend/src/constants/assets.ts
  frontend/src/pages/ClientPage.tsx
  frontend/src/pages/ErrorPage.tsx
  frontend/src/pages/HostPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/ReplayPage.tsx
  yarn.lock
Labels: BE🐹, REFACTOR, FIX, FE🎄
